pipeline {
  agent { label 'rhel-test' }
    // environment {
    // EXTRA= "your path needs here"
    //   }
  stages {

    stage('Setup') {
      steps {
        // withEnv(["PATH+EXTRA=$EXTRA"]) { ##this is how you'd add path to this stage
        // sh 'chef shell-init sh' ## this is if chef shell env isn't seeing everything
        sh 'echo "Versions: "'
        sh 'chef --version'
        sh 'rubocop --version'
        sh 'foodcritic --version'
        sh 'echo "Updating Berkshelf: "'
        sh 'if [ ! -f Policyfile.rb ]; then chef install Policyfile.rb; else echo nothing; fi;' // would like to come back and add more pieces to policy promotion but need time work out kinks
      }
    }

stage('Acceptance Testing') {
      steps {
            parallel(
              Rubocop: {
            sh'echo "Starting chefstyle (rubocop): "'
            sh'rubocop --color'
              },
              FoodCritic: {
            sh'echo "Starting foodcritic: "'
            sh'foodcritic . --tags -FC078'
              },
              ChefSpec: {
            sh'echo Starting ChefSpec: '
            sh'chef exec rspec'
              }
            )
          }
        }


    stage('Test Kitchen') {
      steps {
        sh 'kitchen test -d always --color'
      }
    }
  }

// below i am doing branch checking and pull requests based on non-master to master. could be a cleaner way but haven't finished development
  post {
    success {
      script{
      if( env.BRANCH_NAME == 'dev' ) {
        sshagent(credentials: ['jenkins-generated-ssh-key']) {
        sh 'git request-pull -p origin/master git@gitlab.com:jbrimager/audit_wrap.git dev'
        }
      } else if (env.BRANCH_NAME == 'master') {
          echo "berks or policyfile upload steps here"  // this will include chef repo pieces
        } 
      }
    }
    failure {
      echo "The build failed"
      sh "sudo rm -rf $WORKSPACE/*"
      }
    }
  }  